### ISSUE TITLE
Deprecation error for html, js output format in php7.4

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [flack/UniversalFeedCreator#11]
When I choose HTML as feed output, I get this deprecation error in php7.4:

'join(): Passing glue string after array is deprecated. Swap the parameters'

```
in: /var/www/html/vendor/openpsa/universalfeedcreator/lib/Creator/HTMLCreator.php
line 143:
$feed = "".join($feedArray, "\r\n");
```

(or another file for js type)

**Comment by flack** [comment]
Thanks for the report! I pushed a fix & published a release, so it should work now

**Comment by 24HOURSMEDIA** [comment]
thank you!
