### ISSUE TITLE
is .github/workflows/php.yml meant to be in the release?

### ISSUE THREAD

**Issue by dlangille** [flack/UniversalFeedCreator#13]
In the latest release, a new file showed up:

`.github/workflows/php.yml`

Is it meant to be there?

**Comment by flack** [comment]
Yes, it's part of the migration to Github CI, as mentioned in the release notes. See also: https://github.com/flack/UniversalFeedCreator/actions/workflows/php.yml

**Comment by dlangille** [comment]
I'll be installing from a FreeBSD package (which I'm updating to this release) - must this file be installed?

**Comment by flack** [comment]
No, it's not used at all during runtime, it's only needed to run unit tests on Guthub. You can totally ignore/remove it
