### ISSUE TITLE
lastBuildDate off by one hour

### ISSUE THREAD

**Issue by dlangille** [flack/UniversalFeedCreator#6]
I have not tracked down the issue yet, but lastBuildDate forrss0.91 & rss2.0 at https://www.freshports.org/backend/ is off by one hour.

e.g. Mon, 31 Jul 2017 02:33:29 +0000 when the time on the system is Mon Jul 31 01:33:29 UTC 2017

**Comment by dlangille** [comment]
FYI, the same problem occurs at http://dev.freshports.org/backend/

**Comment by flack** [comment]
Do you set the 'lastBuildDate' manually in your code or is it the default from `FeedCreator`? Also, what timezone is your PHP using?

**Comment by dlangille** [comment]
The code is not setting `lastBuildDate` as confirmed via `grep -ri lastBuildDate *`

The output of `phpinfo()` shows:

`Default timezone: UTC` and `date.timezone: UTC`

**Comment by flack** [comment]
I've taken a look at this, but the date logic in this code is very weird. It seems to me as though the timezone offset shouldn't be applied. Could you try commenting out this line line

https://github.com/flack/UniversalFeedCreator/blob/master/lib/Element/FeedDate.php#L72

and see if the date is reported correctly afterwards? It worked for me (PHP 7 + CEST), but I'd like some independent confirmation before changing this

**Comment by dlangille** [comment]
Yes, I'll try this right away.  $WORK.

**Comment by dlangille** [comment]
That works.  See http://dev.freshports.org/backend/

NOTE: without the code change, rss1.0 still validates.

Also, with the code change, the validation for rss2.0.php has one recommendation: 'Missing atom:link with rel="self"'.  Shall I open another issue for that one?

**Comment by flack** [comment]
the strange thing is, if the script runs in the UTC timezone, it actually shouldn't make a difference. I just tried locally and it shows the correct time there

**Comment by dlangille** [comment]
This server is on UTC but both it and I are in EST.

```
$ date
Wed Aug  9 13:47:53 UTC 2017

**Comment by flack** [comment]
could you post the output of `date('r')` on the affected system?

**Comment by flack** [comment]
about the rss2.0 validation: yes, a separate ticket would be best

**Comment by dlangille** [comment]
Sorry, I did not see your requests.  Does this help?

```
$ date('r') 
bash: syntax error near unexpected token `'r''
```

**Comment by flack** [comment]
That's not PHP's `date` function, it's the one from Bash. To run PHP directly from the terminal, you can do this:

```bash
php -r 'echo date("r") . "\n";'
```

and then maybe compare it to what `date` (from Bash) returns. It could be that your PHP is set to a different timezone than the machine

**Comment by dlangille** [comment]
Sorry, I didn't think PHP there.

```
$ phpphp -r 'echo date("r") . "\n";'
Sun, 24 Jan 2021 23:36:06 +0000

```

**Comment by flack** [comment]
Do you get the same date when you run this from the webserver process? i.e. not PHP from cli, but php-fpm (or whatever your webserver is using)

**Comment by dlangille** [comment]
`Mon, 25 Jan 2021 00:07:16 +0000` is output by this file:

```
<?php

echo date('r');

```

**Comment by flack** [comment]
yeah well, you need to have PHP installed in the webserver for it to work :-)

**Comment by dlangille** [comment]
PHP is installed.  It worked... the output is before the file. That's the output of the webserver.

**Comment by flack** [comment]
ah, sorry, I must have missed one of the notifications, only saw the last message. Ok, so cli and the server report the same time. But it's still off by one hour in UniversalFeedCreator?

**Comment by dlangille** [comment]
It is correct.  So...

```
        <lastBuildDate>Mon, 25 Jan 2021 01:17:37 +0000</lastBuildDate>
$ date
Mon Jan 25 01:17:42 UTC 2021
```

I do know that I upgraded 1.8.3.1 -> 1.8 and it has been more than three years since I last tried this. Many things have changed. :/

**Comment by flack** [comment]
well, who knows. Maybe some cofnig somewhere else on the machine changed in the meantime. In any case, it doesn't seem to be related to the FeedCrerator code.

**Comment by dlangille** [comment]
> well, who knows. Maybe some cofnig somewhere else on the machine changed in the meantime. In any case, it doesn't seem to be related to the FeedCrerator code.

This has been found: `date_default_timezone_set('Europe/London');`

This old post helped me track down the problem.  Cheers.
